In [1]:
import pandas as pd

# Import the dataset
file_path = "./NY_House_Dataset.csv"  # Adjust path if necessary
ny_house_dataset = pd.read_csv(file_path)

# Display the dataset
ny_house_dataset.head()

,BROKERTITLE,TYPE,PRICE,BEDS,BATH,PROPERTYSQFT,ADDRESS,STATE,MAIN_ADDRESS,ADMINISTRATIVE_AREA_LEVEL_2,LOCALITY,SUBLOCALITY,STREET_NAME,LONG_NAME,FORMATTED_ADDRESS,LATITUDE,LONGITUDE
0,Brokered by Douglas Elliman -111 Fifth Ave,Condo for sale,315000,2,2.000000,1400.0,2 E 55th St Unit 803,"New York, NY 10022","2 E 55th St Unit 803New York, NY 10022",New York County,New York,Manhattan,East 55th Street,Regis Residence,"Regis Residence, 2 E 55th St #803, New York, N...",40.761255,-73.974483
1,Brokered by Serhant,Condo for sale,195000000,7,10.000000,17545.0,Central Park Tower Penthouse-217 W 57th New Yo...,"New York, NY 10019",Central Park Tower Penthouse-217 W 57th New Yo...,United States,New York,New York County,New York,West 57th Street,"217 W 57th St, New York, NY 10019, USA",40.766393,-73.980991
2,Brokered by Sowae Corp,House for sale,260000,4,2.000000,2015.0,620 Sinclair Ave,"Staten Island, NY 10312","620 Sinclair AveStaten Island, NY 10312",United States,New York,Richmond County,Staten Island,Sinclair Avenue,"620 Sinclair Ave, Staten Island, NY 10312, USA",40.541805,-74.196109
3,Brokered by COMPASS,Condo for sale,69000,3,1.000000,445.0,2 E 55th St Unit 908W33,"Manhattan, NY 10022","2 E 55th St Unit 908W33Manhattan, NY 10022",United States,New York,New York County,New York,East 55th Street,"2 E 55th St, New York, NY 10022, USA",40.761398,-73.974613
4,Brokered by Sotheby's International Realty - E...,Townhouse for sale,55000000,7,2.373861,14175.0,5 E 64th St,"New York, NY 10065","5 E 64th StNew York, NY 10065",United States,New York,New York County,New York,East 64th Street,"5 E 64th St, New York, NY 10065, USA",40.767224,-73.969856

In [2]:
columns_to_keep = ["PRICE", "BEDS", "BATH", "PROPERTYSQFT", "STATE", "TYPE"]

# Keep only selected columns in dataframe
df = ny_house_dataset[columns_to_keep]
df

,PRICE,BEDS,BATH,PROPERTYSQFT,STATE,TYPE
0,315000,2,2.000000,1400.000000,"New York, NY 10022",Condo for sale
1,195000000,7,10.000000,17545.000000,"New York, NY 10019",Condo for sale
2,260000,4,2.000000,2015.000000,"Staten Island, NY 10312",House for sale
3,69000,3,1.000000,445.000000,"Manhattan, NY 10022",Condo for sale
4,55000000,7,2.373861,14175.000000,"New York, NY 10065",Townhouse for sale
...,...,...,...,...,...,...
4796,599000,1,1.000000,2184.207862,"Manhattan, NY 10075",Co-op for sale
4797,245000,1,1.000000,2184.207862,"Rego Park, NY 11374",Co-op for sale
4798,1275000,1,1.000000,2184.207862,"New York, NY 10011",Co-op for sale
4799,598125,2,1.000000,655.000000,"Elmhurst, NY 11373",Condo for sale
4800,349000,1,1.000000,750.000000,"Brooklyn, NY 11224",Co-op for sale

In [3]:
# Convert numerical values to int
columns_to_convert = ["PRICE", "BEDS", "BATH", "PROPERTYSQFT"]
df.loc[:, columns_to_convert] = df[columns_to_convert].apply(pd.to_numeric, errors='coerce').fillna(0).astype(int)
df

,PRICE,BEDS,BATH,PROPERTYSQFT,STATE,TYPE
0,315000,2,2.0,1400.0,"New York, NY 10022",Condo for sale
1,195000000,7,10.0,17545.0,"New York, NY 10019",Condo for sale
2,260000,4,2.0,2015.0,"Staten Island, NY 10312",House for sale
3,69000,3,1.0,445.0,"Manhattan, NY 10022",Condo for sale
4,55000000,7,2.0,14175.0,"New York, NY 10065",Townhouse for sale
...,...,...,...,...,...,...
4796,599000,1,1.0,2184.0,"Manhattan, NY 10075",Co-op for sale
4797,245000,1,1.0,2184.0,"Rego Park, NY 11374",Co-op for sale
4798,1275000,1,1.0,2184.0,"New York, NY 10011",Co-op for sale
4799,598125,2,1.0,655.0,"Elmhurst, NY 11373",Condo for sale
4800,349000,1,1.0,750.0,"Brooklyn, NY 11224",Co-op for sale

In [4]:
# Use loc, for assigning the columns directly
# Extract only relevant strings
df.loc[:, 'STATE'] = df['STATE'].str.split().str[-1]  # Because ZIP is last string
df.loc[:, 'TYPE'] = df['TYPE'].str.split().str[0]  # Because Type is first string
df

          PRICE  BEDS  BATH  PROPERTYSQFT  STATE       TYPE
0        315000     2   2.0        1400.0  10022      Condo
1     195000000     7  10.0       17545.0  10019      Condo
2        260000     4   2.0        2015.0  10312      House
3         69000     3   1.0         445.0  10022      Condo
4      55000000     7   2.0       14175.0  10065  Townhouse
...         ...   ...   ...           ...    ...        ...
4796     599000     1   1.0        2184.0  10075      Co-op
4797     245000     1   1.0        2184.0  11374      Co-op
4798    1275000     1   1.0        2184.0  10011      Co-op
4799     598125     2   1.0         655.0  11373      Condo
4800     349000     1   1.0         750.0  11224      Co-op

[4801 rows x 6 columns]

In [5]:
# For oversight
unique_type = df['TYPE'].unique()
print(unique_type)

['Condo' 'House' 'Townhouse' 'Co-op' 'Multi-family' 'For' 'Contingent'
 'Land' 'Foreclosure' 'Pending' 'Coming' 'Mobile' 'Condop']

In [6]:
# For oversight
unique_state = df['STATE'].unique()
print(unique_state)

['10022' '10019' '10312' '10065' '11238' '10027' '10304' '10473' '11230'
 '10451' '10303' '11372' '11373' '10014' '11377' '11209' '10471' '11374'
 '10301' '11375' '10465' '10307' '11435' '11214' '10314' '11207' '11219'
 '11355' '11249' '10453' '11204' '11421' '10012' '11358' '11419' '10013'
 '11231' '11217' '10023' '11235' '10002' '11218' '10306' '10308' '10075'
 '11221' '11237' '11357' '10305' '11385' '10466' '11422' '10128' '10010'
 '11436' '11234' '10025' '11210' '10021' '10463' '10469' '10470' '10309'
 '11229' '11215' '10029' '10031' '11228' '10467' '11208' '11417' '11413'
 '10032' '11691' '11426' '10007' '11360' '11103' '11005' '11365' '10458'
 '10024' '11697' '10452' '11414' '11411' '11224' '11694' '10280' '11201'
 '11369' '11362' '10474' '11354' '11415' '10038' '11105' '11216' '10302'
 '11368' '11223' '10011' '10016' '10462' '10475' '11212' '11205' '11203'
 '10036' '10028' '10017' '10033' '11236' '10310' '10006' '10001' '11226'
 '10040' '11378' '10003' '10069' '10472' '11429' '11418' '11379' '11412'
 '10464' '10009' '11420' '10460' '11356' '10030' '11432' '10457' '11233'
 '10461' '11361' '10005' '11211' '11220' '10454' '11693' '10026' '11363'
 '11367' '10034' '11423' '11366' '11225' '11232' '10004' '10035' '10044'
 '11101' '11004' '10037' '11104' '11692' '11433' '10018' '10456' '10459'
 '11222' '11213' '10468' '11370' '11040' '11109' '11427' '11001' '11102'
 '11106' '11206' '11364' '10455' '10039' '10282' '11416']

In [7]:
# For oversight
# Sort unique values after numerical size for oversight
unique_state_sorted = sorted(unique_state, key=lambda x: int(x))

# Print sorted values
print(unique_state_sorted)

['10001', '10002', '10003', '10004', '10005', '10006', '10007', '10009', '10010', '10011', '10012', '10013', '10014', '10016', '10017', '10018', '10019', '10021', '10022', '10023', '10024', '10025', '10026', '10027', '10028', '10029', '10030', '10031', '10032', '10033', '10034', '10035', '10036', '10037', '10038', '10039', '10040', '10044', '10065', '10069', '10075', '10128', '10280', '10282', '10301', '10302', '10303', '10304', '10305', '10306', '10307', '10308', '10309', '10310', '10312', '10314', '10451', '10452', '10453', '10454', '10455', '10456', '10457', '10458', '10459', '10460', '10461', '10462', '10463', '10464', '10465', '10466', '10467', '10468', '10469', '10470', '10471', '10472', '10473', '10474', '10475', '11001', '11004', '11005', '11040', '11101', '11102', '11103', '11104', '11105', '11106', '11109', '11201', '11203', '11204', '11205', '11206', '11207', '11208', '11209', '11210', '11211', '11212', '11213', '11214', '11215', '11216', '11217', '11218', '11219', '11220', '11221', '11222', '11223', '11224', '11225', '11226', '11228', '11229', '11230', '11231', '11232', '11233', '11234', '11235', '11236', '11237', '11238', '11249', '11354', '11355', '11356', '11357', '11358', '11360', '11361', '11362', '11363', '11364', '11365', '11366', '11367', '11368', '11369', '11370', '11372', '11373', '11374', '11375', '11377', '11378', '11379', '11385', '11411', '11412', '11413', '11414', '11415', '11416', '11417', '11418', '11419', '11420', '11421', '11422', '11423', '11426', '11427', '11429', '11432', '11433', '11435', '11436', '11691', '11692', '11693', '11694', '11697']

In [8]:
# Execute One-hot encoding for the columns 'STATE' and 'TYPE'
df_encoded = pd.get_dummies(df, columns=['STATE', 'TYPE'], prefix=['STATE', 'TYPE'])
df_encoded

,PRICE,BEDS,BATH,PROPERTYSQFT,STATE_10001,STATE_10002,STATE_10003,STATE_10004,STATE_10005,STATE_10006,...,TYPE_Condop,TYPE_Contingent,TYPE_For,TYPE_Foreclosure,TYPE_House,TYPE_Land,TYPE_Mobile,TYPE_Multi-family,TYPE_Pending,TYPE_Townhouse
0,315000,2,2.0,1400.0,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,195000000,7,10.0,17545.0,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,260000,4,2.0,2015.0,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
3,69000,3,1.0,445.0,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,55000000,7,2.0,14175.0,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4796,599000,1,1.0,2184.0,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4797,245000,1,1.0,2184.0,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4798,1275000,1,1.0,2184.0,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4799,598125,2,1.0,655.0,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4800,349000,1,1.0,750.0,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [9]:
print(df_encoded.shape)

(4801, 195)

In [10]:
# Analysing upper outliers
top_10_prices = df_encoded["PRICE"].nlargest(20)
print(top_10_prices)

304     2147483647
1        195000000
69        65000000
1075      60000000
141       56000000
4         55000000
99        55000000
626       50000000
1453      48000000
3388      45000000
3571      44500000
1465      40000000
181       39995000
2107      36000000
1258      34000000
2706      32000000
4466      32000000
4623      31500000
76        31000000
1388      30000000
Name: PRICE, dtype: int64

In [11]:
# Removing upper outliers based on 99. percentile
def remove_upper_outliers(df, columns, percentile=0.99):
    for col in columns:
        upper_limit = df[col].quantile(percentile)
        df = df[df[col] <= upper_limit]
    return df


# Remove datapoint with upper outliers in df
df_encoded = remove_upper_outliers(df_encoded, ['PRICE'])

# Statistic of cleaned dataframe
print(df_encoded.describe())

              PRICE         BEDS         BATH  PROPERTYSQFT
count  4.754000e+03  4754.000000  4754.000000   4754.000000
mean   1.575506e+06     3.331510     2.316155   2118.077829
std    2.502621e+06     2.595191     1.907818   2074.812363
min    2.494000e+03     1.000000     0.000000    230.000000
25%    4.950000e+05     2.000000     1.000000   1200.000000
50%    8.025000e+05     3.000000     2.000000   2184.000000
75%    1.450000e+06     4.000000     3.000000   2184.000000
max    2.250000e+07    50.000000    50.000000  55300.000000

In [12]:
# Check highest price again
top_10_prices = df_encoded["PRICE"].nlargest(20)
print(top_10_prices)

1215    22500000
2947    22500000
3338    22500000
3940    21500000
4533    21000000
4733    21000000
4746    21000000
1825    19995000
2251    19995000
2697    19995000
3818    19995000
4347    19995000
3654    19500000
1733    19499999
3714    18950000
2299    18500000
3666    18000000
1863    17995000
680     17900000
126     17500000
Name: PRICE, dtype: int64

In [13]:
# Save the modified DataFrame to a new CSV file
output_file_path = "./Clean_NY.csv"
df_encoded.to_csv(output_file_path, index=False)